server:
  port: 8989

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    hostname: localhost


#spring:
#  cloud:
#    config:
#      uri:
#        - https://localhost:9196

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
        
      - id: payment-service
        uri: lb://payment-service
        predicates:
        - Path=/payment/**    
    
