server:
  port: 9197
  
    
spring:
#  cloud:
#    config:
#      uri:
#        - http://localhost:9196
#        
  application:
    name: payment-service
#  config:
#    import:
#    -  "optional:configserver:"  
    
  datasource:
    hikari:
      maximum-pool-size: 8
    url:  jdbc:mysql://localhost:3306/PAYMENT-SERVICE
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
  default_schema: test
  format_sql: true
  generate_statistics: true
  dialect: org.hibernate.dialect.MySQL8Dialect
  dialect.storage_engine: innodb

  
eureka:
  instance:
  prefer-ip-address: true
  instance-id : ${spring.cloud.client.ip-address}:${server.port}
  hostname:  localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/